### ISSUE TITLE
Use ingress to access webui

### ISSUE THREAD

**Issue by Pulpyyyy** [Pulpyyyy/carconnectivity-addon#25]

**Comment by jressel01** [comment]
think code was as mine now. you are on discord?

**Comment by Pulpyyyy** [comment]
I think we are ok.

Tillsteinbach released v0.2

Release ?

**Comment by jressel01** [comment]
Try build think it work. Make pre-release

**Comment by Pulpyyyy** [comment]
Pre-release (and release as well) are not fine, as the latest commit in main branch is used by HA when retrieving content.
I opened a issue to improve the way it works https://github.com/Pulpyyyy/carconnectivity-addon/issues/22

**Comment by jressel01** [comment]
fix build error with 0.1.4
Till change mqtt ha to vers. 0.1.1 :(

**Comment by jressel01** [comment]
yes i can access Projekt.
try many ways but i dont get ingress to work. in the moment i have no idea

**Comment by Pulpyyyy** [comment]
I came up with something which seems correct. Still a few problems with CSS

![Image](https://github.com/user-attachments/assets/281a0986-8b09-4545-999f-cc46239bb2bc)

config.yaml sample
```
name: "CarConnectivity Addon edge"
version: 0.2.3
slug: "carconnectivity-addon-edge"
description: "⚠️EDGE VERSION⚠️ Addon version of Carconnectivity made by Till (see https://github.com/tillsteinbach/CarConnectivity) throught MQTT. ⚠️MAY BE INSTABLE⚠️ "
panel_icon: "mdi:car-wireless"
map:
  - addon_config:rw
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ingress: true
ingress_port: 4000
ingress_entry: /login?next=/garage/
ingress_stream: false
ports:
  4000/tcp: 4000
ports_description:
  4000/tcp: Carconnectivity web interface
options:
  connector_type_brand1: "seat"
  connector_username_brand1: ""
  connector_password_brand1: "password"
  connector_spin_brand1: "1234"
  connector_interval_brand1: 600
  connector_type_brand2: "skoda"
  connector_username_brand2: ""
  connector_password_brand2: "password"
  connector_spin_brand2: "1234"
  connector_interval_brand2: 600
  connector_volvo_key_primary: ""
  connector_volvo_key_secondary: ""
  connected_volvo_vehicule_token: ""
  connector_volvo_location_token: ""
  connector_volvo_interval: 600
  mqtt_username: ""
  mqtt_password: ""
  mqtt_broker: "core-mosquitto.local.hass.io"
  mqtt_port: "1883"
  log_level: "info"
  connector_username_webui: "admin"
  connector_password_webui: "secret"
  api_log_level: "info"
  expert: false
schema:
  connector_type_brand1: list(seat|cupra|skoda|volkswagen|trionity)
  connector_username_brand1: match(^$|^[\w\-\.]+@([\w-]+\.)+[\w-]{2,}$)
  connector_password_brand1: password?
  connector_interval_brand1: int(60,3600)?
  connector_spin_brand1: match(^\d{4}$)?
  connector_type_brand2: list(seat|cupra|skoda|volkswagen|trionity)
  connector_username_brand2: match(^$|^[\w\-\.]+@([\w-]+\.)+[\w-]{2,}$)
  connector_password_brand2: password?
  connector_interval_brand2: int(60,3600)?
  connector_spin_brand2: match(^\d{4}$)?
  connector_volvo_key_primary: str?
  connector_volvo_key_secondary: str?
  connected_volvo_vehicule_token: str?
  connector_volvo_location_token: str?
  connector_volvo_interval: int(60,3600)?
  mqtt_username: str?
  mqtt_password: password?
  mqtt_broker: str
  mqtt_port: int
  log_level: list(info|warning|error|debug)
  connector_username_webui: str
  connector_password_webui: password?
  api_log_level: list(info|warning|error|debug)
  expert: bool
```
