### ISSUE TITLE
Position entity is "unknown"

### ISSUE THREAD

**Issue by kRew94** [Pulpyyyy/carconnectivity-addon#8]
Hey,
The Position entity is shown as "unknown" for my Cupra Formentor eHybrid.
The Latitude and Longitude entities show the correct values.
![Image](https://github.com/user-attachments/assets/17ece356-0679-4910-9aaa-72715085acc3)

**Workaround**
Created the following automation that generates a device_tracker for the car:

```
alias: Cupra_Formentor_GPS_Position
description: "Create a device_tracker with Latitude and Longitude sensors"
trigger:
  - platform: state
    entity_id: 
      - sensor.cupra_formentor_position_latitude
      - sensor.cupra_formentor_position_longitude
action:
  - service: device_tracker.see
    data_template:
      dev_id: cupra_formentor
      gps:
        - "{{ states('sensor.cupra_formentor_position_latitude') }}"
        - "{{ states('sensor.cupra_formentor_position_longitude') }}"
```
